### ISSUE TITLE
inclusion in coredns

### ISSUE THREAD

**Issue by miekg** [serverwentdown/dns64#1]
I think this is a good plugin to have by default. @fturib (I think?) expressed interest as well. Could you possibly work together and push for upstream inclusion?

**Comment by serverwentdown** [comment]
At this point, I think this plugin shouldn't be included in upstream yet as it's proxying mechanism is not ideal. It really needs more refinement, and I am awaiting for more free time to try a different approach, probably using `dnsserver.GetConfig(c)`.

**Comment by serverwentdown** [comment]
Other than that, I can see this plugin being included upstream in the future.

**Comment by fturib** [comment]
I agree, it would be good to have this plugin by default.

@serverwentdown : include me when you start to work again on this plugin.

**Comment by serverwentdown** [comment]
I made some changes to the plugin, and I think it's okay to include it upstream.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [serverwentdown/dns64] inclusio..." ]
>I made some changes to the plugin, and I think it's okay to include it upstream.

OK, please open a PR to do so.

Thanks!

**Comment by SuperQ** [comment]
@serverwentdown Any progress on this? I'm happy to help move this along.

**Comment by serverwentdown** [comment]
Wanted to rewrite this before doing a PR for introduction into upstream because the code isn't written well at all, but haven't found the time. Thanks for making the move.

**Comment by SuperQ** [comment]
My only motivation is to get it done soon so I can more easily use the code for FOSDEM. If it's possible to do your re-work in the next couple weeks, that would be good.

**Comment by SuperQ** [comment]
https://github.com/coredns/coredns/pull/3534 is now merged upstream. :tada:

**Comment by serverwentdown** [comment]
@SuperQ Awesome work!
