### ISSUE TITLE
Feature request; Force A (ipv4) external queries

### ISSUE THREAD

**Issue by uablrek** [serverwentdown/dns64#3]
**Feature Request**

I am testing Kubernetes ipv6-only in a ipv4-only environment (company IT network). A problem is that when a process in the ipv6 space makes a AAAA query the DNS may actually get a AAAA response and (correctly) return it to the process.

The problem is that my ipv6 test environment does not have ipv6 access to the internet for reasons out of my control.

I would like a configuration option that forces *all* external queries to be A (ipv4) and be translated to ipv6 using the prefix. E.g; `translateAll: yes`.

I have not even included CoreDNS+dns64 in my Kubernetes ipv6-only cluster yet, so if this can already be configured I apologize, but if so, please update the documentation.

In `bind9` this can be done with an `exclude { any; }` in the `dns64` configuration. As a work-around I can use a local bind9 but then I would not test the coredns dns64 plugin properly.

**Comment by serverwentdown** [comment]
I'm not really free right now to help implement it but modifying `dns64.go` on [L83](https://github.com/serverwentdown/dns64/blob/master/dns64.go#L83) and [L58](https://github.com/serverwentdown/dns64/blob/master/dns64.go#L58) with conditions to allow all AAAA requests on L58 but drop them and translate the A requests to AAAA before L83.
