### ISSUE TITLE
Build failed with recent coredns

### ISSUE THREAD

**Issue by Zhuul** [serverwentdown/dns64#9]
Hi,

I'm trying to build DNS64 plugin with recent coredns code and  github.com/missdeer/proxy (an updated version of github.com/coredns/proxy)  in a go1.13 fresh docker env and get this error when I add DNS64 plugin : 
```
# GO111MODULE=auto go clean -modcache && GO111MODULE=auto go mod tidy && GO111MODULE=auto go build
<...>
go: finding golang.org/x/text v0.3.2
go: finding gopkg.in/square/go-jose.v2 v2.3.1
# github.com/serverwentdown/dns64
./dns64.go:65:22: r.DNS64.Proxy.Lookup undefined (type proxy.Proxy has no field or method Lookup)
./setup.go:60:12: undefined: proxy.NewLookup
#
```

Beside I "generated" a go.mod for DNS64  plugin (unsure if it was necessary) :
 
```

module github.com/serverwentdown/dns64

go 1.13

replace (
        github.com/coredns/coredns v1.6.3 => /go/src/github.com/coredns/coredns
        github.com/miekg/dns v1.1.3 => github.com/miekg/dns v1.1.17
        github.com/missdeer/proxy v0.0.0-20190830011929-ab38cbb8fdfa => /go/src/github.com/missdeer/proxy
        golang.org/x/net v0.0.0-20190813000000-74dc4d7220e7 => golang.org/x/net v0.0.0-20190813141303-74dc4d7220e7
)

require (
        github.com/caddyserver/caddy v1.0.3
        github.com/coredns/coredns v1.6.3
        github.com/dnstap/golang-dnstap v0.1.0 // indirect
        github.com/farsightsec/golang-framestream v0.0.0-20190425193708-fa4b164d59b8 // indirect
        github.com/klauspost/cpuid v1.2.1 // indirect
        github.com/mholt/certmagic v0.7.0 // indirect
        github.com/miekg/dns v1.1.17
        github.com/missdeer/proxy v0.0.0-20190830011929-ab38cbb8fdfa
        github.com/prometheus/client_model v0.0.0-20190812154241-14fe0d1b01d4 // indirect
        github.com/prometheus/procfs v0.0.4 // indirect
        golang.org/x/net v0.0.0-20190912160710-24e19bdeb0f2 // indirect
        golang.org/x/sys v0.0.0-20190912141932-bc967efca4b8 // indirect
        google.golang.org/genproto v0.0.0-20190911173649-1774047e7e51 // indirect
        google.golang.org/grpc v1.23.1 // indirect
)


```

I may have done something wrong (I am totally unfamiliar/new to Go..). 

Except for DNS64 plugin everything compiles and works (coredns & the external proxy plugin). But I  don't know how to solve this DNS64 error neither exactly where it's coming from.. maybe the proxy plugin or coredns version I'm using  are too recent ? I just don't know.

 Some help would be nice. Thanks.

**Comment by serverwentdown** [comment]
Recently, the Proxy plugin changed their API. I'm figuring out a way to ensure this plugin won't depend on the Proxy plugin directly. My initial assessment is to turn this plugin into a fork of either 'forward' or 'proxy' and add the rewrite into it.

**Comment by chrisohaver** [comment]
Once you pass the proxy issue,  `github.com/mholt/caddy` has moved to `github.com/caddyserver/caddy`.
